name: Skematic
author: Efnilite
description: Skript addon for pasting and saving schematics
version: 3.0.1
api-version: 1.20
main: dev.efnilite.skematic.Skematic
depend: [Skript]
commands:
  skematic:
    description: Main command for Skematic