name: Skematic
author: Efnilite
description: Skript addon for pasting and saving schematics
version: 3.0.4
api-version: 1.20
main: dev.efnilite.skematic.Skematic
depend: [Skript]
website: https://github.com/Efnilite/skematic
commands:
  skematic:
    description: Main command for Skematic